before_install:
    - sudo add-apt-repository ppa:pi-rho/security -y
    - sudo apt-get update -qq
    - sudo apt-get install -y pkg-config libjansson-dev

language: c

compiler:
    - clang
    - gcc

script: make check
